blog/just_keeley/config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'

  root "posts#index"
  
  resources :posts do
    resources :comments
  end
  
  get "/about", to: 'pages#about' 

end

blog/just_keeley/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

blog/just_keeley/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

blog/just_keeley/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

blog/just_keeley/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

blog/just_keeley/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body,  presence: true
end

blog/just_keeley/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/just_keeley/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/just_keeley/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

end

blog/just_keeley/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
	def about
	end

end

blog/just_keeley/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]



  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to @post
    else
      flash[:alert] = "Error creating new post!"
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      flash[:notice] = "Successfully updated post!"
      redirect_to @post
    else
      flash[:alert] = "Error updating post!"
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end



end

blog/just_keeley/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/just_keeley/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/just_keeley/app/helpers/pages_helper.rb
module PagesHelper
end

blog/just_keeley/app/helpers/posts_helper.rb
module PostsHelper
end

blog/just_keeley/app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

  <% if user_signed_in? %>
  <p><%= link_to 'Delete', [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?' } %></p>
  <% end %>
</div>

blog/just_keeley/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

blog/just_keeley/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>JustKeeley</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Playfair+Display:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.icon' %>

</head>
<body>



<!--<nav class="navbar navbar-default navbar-fixed-top " role="navigation" id="blognav">
        <div class="container">
            <ul class="row">
                <li class="col-sm-1 col-sm-offset-3"><a href="#promise"> Promise </a></li>
                <li class="col-sm-1"><a href="#aboutk"><span style="float:right"> About </span></a></li>
                    <a href="home.html"><li class="col-sm-2" id="navlogo"></li></a>
                <li class="col-sm-1"><a href="blog.html"> Blog </a></li>
                <li class="col-sm-1"><a href="#contact"> Contact </a></li>
            </ul>
        </div> 
    </nav> -->

  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
      <% end %>
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://twitter.com/">Twitter</a></li>
      <li><a href="http://instagram.com/">Instagram</a></li>
      <li><a href="https://github.com/">Github</a></li>
      <li><a href="https://gmail.com">Email</a></li>
    </ul>


    <%= if !user_signed_in? %>
      <p class="sign_in">Admin Login<%= link_to "Admin Login", new_user_session_path %></p>
    <% end %>

  </div>

  <div id="main_content">
    <div id="header">

      <% if current_page?(root_path) %>
        <p>All Posts</p>

      <%= elsif current_page?(about_path) %>
         <p>About</p> 

      <% else %>
        <%= link_to "Back to All Posts", root_path %>
      <% end %>

      <%= if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button">Log Out</button>
        </div>
      <%= end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

blog/just_keeley/app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>

	<div id="content">
		<h1>Hey, I'm Keeley Nicole</h1>
		<p>Welcome to my blog!</p>
		<p>This week I built a blog in Rails. You're actually on the demo application right now. Cool stuff, right!.</p>
		<p>get my posts and exclusive content in your inbox by signing up for my newsletter <a href="http://eepurl.com/02olT">here</a>.</p>
	</div>
</div>

blog/just_keeley/app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
<%# form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>

  <!--
  <%# f.label :title %><br> 
  <%# f.text_field :title %><br>
  <br>
  <%# f.label :body %><br>
  <%# f.text_field :body %><br>
  <br>
  <%# f.submit %> 
  -->

<% end %>

blog/just_keeley/app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h2>Edit Post</h2>

  <%= render "posts/form" %>
</div>

blog/just_keeley/app/views/posts/index.html.erb
<% @posts.each do |post| %>

  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>

    <p class="date"><%= post.created_at.strftime('%b %d, %Y') %></p>
  </div>

  <div>
    <%= raw(post.body).truncate(358) %>
  </div>

<% end %>

blog/just_keeley/app/views/posts/new.html.erb
<div id="page_wrapper">

  <h2>New Post</h2>

  <%= render "posts/form" %>

</div>

blog/just_keeley/app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"><%= @post.title %></h1>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <%= if user_signed_in? %>
    | <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <p class="body">
    <%= raw @post.body %></p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>